name: peer-to-peer-to-me-challenge
services:
  launcher:
    environment:
      CHALLENGE: peer-to-peer-to-me
      FLAG: "SECRET"
    container_name: peer-to-peer-to-me
    image: peer-to-peer-to-me
    build:
      context: .
      target: chroot
    command: socat TCP-LISTEN:1337,reuseaddr,fork exec:"python3 -u challenge/challenge.py"
    expose:
      - 1337
    ports:
      - "1337:1337"
    networks:
      - ctf_network
networks:
  ctf_network:
    name: remedyctf
    external: true
