name: world-of-memecraft-challenge
services:
  launcher:
    environment:
      CHALLENGE: world-of-memecraft
      FLAG: "SECRET"
    container_name: world-of-memecraft
    image: world-of-memecraft
    build:
      context: .
      target: chroot
    command: socat TCP-LISTEN:1337,reuseaddr,fork exec:"python3 -u challenge/challenge.py"
    expose:
      - 1337
    ports:
      - "1337:1337"
    networks:
      - ctf_network
networks:
  ctf_network:
    name: remedyctf
    external: true
